
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    credentials:
      access-key: AKIAW3MEASDQTJ2Z2GPQ
      secret-key: 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
    region:
      static: sa-east-1