
spring:
  profiles:
    active: dev

cloud:
  aws:
    credentials:
      access-key: AKIAW3MEASDQTJ2Z2GPQ
      secret-key: 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
    region:
      static: sa-east-1