server:
  port: 9090

spring:
 h2:
   console:
     enabled: true
     path: /h2
 jpa:
   hibernate:
     ddl-auto: create-drop
   open-in-view: false
 datasource:
   url: jdbc:h2:file:~/divulgacao_fsc
   username: sa
   password:
   driverClassName: org.h2.Driver

cloud:
  aws:
    bucket: fcs-bucket-supplier-dev